version: '3.8'

services:
  postgres-test:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: banking_poc_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d banking_poc_test"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - test-network

  postgres-dev:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: banking_poc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d banking_poc"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - test-network

volumes:
  postgres_test_data:
  postgres_dev_data:

networks:
  test-network:
    driver: bridge